### ISSUE TITLE
Doesn't work with 10.14.3

### ISSUE THREAD

**Issue by Tonyliu2ca** [AlexanderWillner/runMacOSinVirtualBox#51]
**To Reproduce**
after installed Mojave 10.14.3, it won't start.

**Comment by AlexanderWillner** [comment]
Can you be more specific? See screenshot:

<img width="1626" alt="screenshot 2019-01-27 at 19 20 22" src="https://user-images.githubusercontent.com/307605/51805201-db24a380-226a-11e9-83a5-fba12a07ec85.png">

In case you mean the 10.14.3 installer doesn't start but instead the 10.14.2 OS boots up again, this was just fixed in c3190cc. Run ```make patch``` again.
