### ISSUE TITLE
Very poor performance on macOS 10.15

### ISSUE THREAD

**Issue by EdwardHinkle** [AlexanderWillner/runMacOSinVirtualBox#71]
I downloaded the 10.15 beta and ran the script, but there is VERY poor performance. Example, you can't drag a window or scroll the scrollbar with the mouse. You can only click place. The mouse will blink in and out while it moves across screen, animations are delayed, etc.

Does anyone have this working decently on the 10.15 beta? My goal was to be able to use Xcode 11 but the performance is so bad, I don't think it's even usable for that.

**Comment by AlexanderWillner** [comment]
Currently not using/testing actively. However, you might try reducing transparency and motion as there is no GPU support: http://osxdaily.com/2018/12/17/how-reduce-motion-mac-disable-animations/ and http://osxdaily.com/2016/01/02/disable-transparency-effects-mac-os-x/

**Comment by EdwardHinkle** [comment]
Ohh great idea! I’ll try that out here shortly and report back!

**Comment by advantis** [comment]
@EdwardHinkle I had the same goal (Xcode 11) and the same issue with VirtualBox. I ended up installing Parallels trial and it works much better in terms of performance. However when I try to create/open a project it crashes immediately with stack trace hinting that it's unable to render mini-map because of some Metal issue. Also seems that we can't drag windows not because of poor performance, but because some input peculiarity in Catalina. For Parallels there's a workaround listed in their KB article: https://kb.parallels.com/en/124705. Please let me know if you were able at least create/open a project in VirtualBox?

**Comment by EdwardHinkle** [comment]
Ahhh that makes sense. Well darn, my virtual hard drive is too small to install Xcode and I'm still seeing all the same issues as before turning off the display settings mentioned above. Looks like there are probably just too many issues in the beta to use it in a virtual machine right now (which is too bad since that's the safest way to use it!) So @advantis I wasn't able to install Xcode, so I wasn't able to try to create a project. I resized the HDD in VirtualBox but then I couldn't reformat it within macOS to see the free space. Since it's likely unusable, I'm not gonna bother going through the reinstallation process with a larger hard drive.

@AlexanderWillner Thanks for making such a great simple script! Feel free to do with this issue whatever you like, close it or leave it open so that people investigating Catalina can know the potential existing issues (for no fault of this script!)
