### ISSUE TITLE
The folder '/Volumes/EFI/' already exists!

### ISSUE THREAD

**Issue by lordsyncrus** [AlexanderWillner/runMacOSinVirtualBox#74]
I have this error after adding APFS drivers.

<img width="931" alt="Screenshot 2019-07-01 at 16 56 20" src="https://user-images.githubusercontent.com/30342384/60446492-bd94a500-9c21-11e9-94ae-1640aa9b6afa.png">

**Comment by Waitsnake** [comment]
I had this issue after performing the script a **second time** (first time I stoped the script in the middle, because macOS had asked for more Accessibility rights of the Terminal app that I granted first).
This issue was there even after I delated all the created files in folder /Users/username/VirtualBox VMs/.
With the help of the logfile I saw there was another folder where the script (or the tools the script uses did it?) had created a bunch of files. This files were under /var/root/VirtualBox VMs/.

I delated these files on terminal with:
sudo rm -rf /var/root/VirtualBox\ VMs

Then I could finally repeat the install process.

**Comment by AlexanderWillner** [comment]
Related #76 - need more tests.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. The `eject` function was extended recently. Assuming this will not happen again.

**Comment by michaeldeprospo** [comment]
I am still receiving this error as well when running `make all`

**Comment by AlexanderWillner** [comment]
Then it might be an old folder that still exists. Does the folder "/Volumes/EFI/" exist and it is empty? In this case, you should remove it.

**Comment by michaeldeprospo** [comment]
> Then it might be an old folder that still exists. Does the folder "/Volumes/EFI/" exist and it is empty? In this case, you should remove it.

Yes it does exist and is empty after running `make all`. If I delete it after the script is done running, and start fresh, it recreates it and throws the same error.
